service: sls-calc-service

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:*
      Resource: "*"  

functions:
  calculate:
    handler: handler.calculate
    onError:
      Fn::GetAtt:
        - DlQueue
        - Arn      
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - InQueue
              - Arn
    environment:
      QUEUE_URL: { "Fn::Join" : [ "", [ "https://sqs.", { "Ref" : "AWS::Region" }, ".amazonaws.com/", { "Ref" : "AWS::AccountId" }, "/${self:custom.outQueue}" ] ]  }

resources:
  Resources:
    InQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.inQueue}
    OutQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.outQueue}
    DlQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.dlQueue}

custom:
  inQueue: calculation-in-${self:provider.stage}
  outQueue: calculation-out-${self:provider.stage}
  dlQueue: calculation-dl-${self:provider.stage}
